package GUI;

import Controller.*;
import Controller.ReportGenerator;
import DAO.*;
import entity.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.opencv.core.Core;

/**
 *
 * @author Yunjing Li
 * @version 1.3.0
 * @since 17/11/2014
 */
public class Window extends javax.swing.JFrame {

    CardLayout CLayout = new CardLayout();
    //recordStudentID is to record the student id of current dashboard column for the use of renew visit.
    private int recordStudentID = 0;
    private StuDAO stuDAO = new StuDAO();

    public String getPhotoURL = "";

    /**
     * Creates new form window
     */
    public Window() {
        initComponents();
        setTitle("Student Reception Information System");
        operatePanel.setLayout(CLayout);
        operatePanel.add("welcome", WelcomePanel);
        operatePanel.add("take photo", takePhotoPanel);
        operatePanel.add("report", viewReportPanel);
        operatePanel.add("dashboard", dashBoardPanel);
        operatePanel.add("renew visit", renewVisitPanel);
        operatePanel.add("search students", searchStudentPanel);
        operatePanel.add("create profile", creatProfilePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        reportGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        photo = new javax.swing.JButton();
        report = new javax.swing.JButton();
        searchStu = new javax.swing.JButton();
        operatePanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        takePhotoPanel = new javax.swing.JPanel();
        dashBoardPanel = new javax.swing.JPanel();
        dashButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showAnnounceTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        showVisitTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        getImage = new javax.swing.JLabel();
        getName = new javax.swing.JLabel();
        getGender = new javax.swing.JLabel();
        getBirth = new javax.swing.JLabel();
        getEmail = new javax.swing.JLabel();
        getAddress = new javax.swing.JLabel();
        getNation = new javax.swing.JLabel();
        getReason = new javax.swing.JLabel();
        getLastVisit = new javax.swing.JLabel();
        getPro = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        getID = new javax.swing.JLabel();
        viewReportPanel = new javax.swing.JTabbedPane();
        studentVisitListPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        beginDayStu = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        beginMonthStu = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        beginYearStu = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        endDayStu = new javax.swing.JComboBox();
        endMonthStu = new javax.swing.JComboBox();
        endYearStu = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        stuReportButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cateList = new javax.swing.JComboBox();
        visitFrequencyPanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        beginDayFre = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        beginMonthFre = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        beginYearFre = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        endDayFre = new javax.swing.JComboBox();
        endMonthFre = new javax.swing.JComboBox();
        endYearFre = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        showTable1 = new javax.swing.JTable();
        freReportButton = new javax.swing.JButton();
        cateList1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        renewVisitPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        inputReason = new javax.swing.JTextField();
        renewButton = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        creatProfilePanel = new javax.swing.JPanel();
        creatProButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        crName = new javax.swing.JTextField();
        crBirth = new javax.swing.JTextField();
        crVisit = new javax.swing.JTextField();
        crProgram = new javax.swing.JTextField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        crEmail = new javax.swing.JTextField();
        crNation = new javax.swing.JTextField();
        crAddress = new javax.swing.JTextField();
        lable1 = new javax.swing.JLabel();
        crCategory = new javax.swing.JComboBox();
        searchStudentPanel = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        inputStuId = new javax.swing.JTextField();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 760));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/CarnegieMellonUniversity_wordmark_meitu_2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        photo.setBackground(new java.awt.Color(153, 0, 0));
        photo.setText("Take photo");
        photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoActionPerformed(evt);
            }
        });

        report.setBackground(new java.awt.Color(153, 0, 0));
        report.setText("View report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        searchStu.setBackground(new java.awt.Color(153, 0, 0));
        searchStu.setText("Search Student");
        searchStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(photo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchStu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(photo)
                .addGap(69, 69, 69)
                .addComponent(searchStu)
                .addGap(77, 77, 77)
                .addComponent(report)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        operatePanel.setLayout(new java.awt.CardLayout());

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/welcome_meitu.jpg"))); // NOI18N

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addComponent(jLabel42)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        operatePanel.add(WelcomePanel, "card8");

        javax.swing.GroupLayout takePhotoPanelLayout = new javax.swing.GroupLayout(takePhotoPanel);
        takePhotoPanel.setLayout(takePhotoPanelLayout);
        takePhotoPanelLayout.setHorizontalGroup(
            takePhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        takePhotoPanelLayout.setVerticalGroup(
            takePhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        operatePanel.add(takePhotoPanel, "card2");

        dashButton.setText("Renew Visit");
        dashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashButtonActionPerformed(evt);
            }
        });

        showAnnounceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Time", "Content", "Announcer"
            }
        ));
        jScrollPane2.setViewportView(showAnnounceTable);

        jLabel12.setText("Name");

        jLabel21.setText("Gender");

        jLabel22.setText("Birthday");

        jLabel23.setText("Program");

        jLabel24.setText("Email");

        jLabel25.setText("Address");

        jLabel26.setText("Nationality");

        jLabel27.setText("Last Visit");

        jLabel28.setText("Reason");

        jLabel29.setText("Visit List");

        jLabel30.setText("Announcement");

        showVisitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Time", "Reason", "Category"
            }
        ));
        jScrollPane3.setViewportView(showVisitTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(getImage, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getImage, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );

        getName.setText("here");

        getGender.setText("here");

        getBirth.setText("here");

        getEmail.setText("here");

        getAddress.setText("here");

        getNation.setText("here");

        getReason.setText("here");

        getLastVisit.setText("here");

        getPro.setText("here");

        jLabel40.setText("Student ID");

        getID.setText("here");

        javax.swing.GroupLayout dashBoardPanelLayout = new javax.swing.GroupLayout(dashBoardPanel);
        dashBoardPanel.setLayout(dashBoardPanelLayout);
        dashBoardPanelLayout.setHorizontalGroup(
            dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashBoardPanelLayout.createSequentialGroup()
                        .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(getLastVisit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(0, 544, Short.MAX_VALUE))
                            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28))
                                .addGap(23, 23, 23)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(getName)
                                    .addComponent(getID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(getEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(getAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(getNation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(getReason, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(7, 7, 7))
                                    .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel22)))
                                .addGap(20, 20, 20)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(getPro, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                    .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                        .addComponent(getGender)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(getBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(dashBoardPanelLayout.createSequentialGroup()
                        .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashButton)
                .addGap(39, 39, 39))
        );
        dashBoardPanelLayout.setVerticalGroup(
            dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashBoardPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(getPro))
                                .addGap(18, 18, 18)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(getBirth)))
                            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(getName))
                                .addGap(18, 18, 18)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel40)
                                    .addComponent(getID))
                                .addGap(18, 18, 18)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(getEmail))
                                .addGap(22, 22, 22)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(getAddress))
                                .addGap(18, 18, 18)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(getNation)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelLayout.createSequentialGroup()
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(getGender)
                                    .addComponent(jLabel21))
                                .addGap(148, 148, 148)))))
                .addGap(17, 17, 17)
                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(getReason)
                    .addComponent(jLabel27)
                    .addComponent(getLastVisit))
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashButton)
                .addContainerGap())
        );

        dashBoardPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {getAddress, getBirth, getEmail, getID, getLastVisit, getNation, getPro, getReason});

        operatePanel.add(dashBoardPanel, "card4");

        jLabel3.setText("Input the date range from");

        jLabel4.setText("Day");

        beginDayStu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel5.setText("Month");

        beginMonthStu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        beginMonthStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginMonthStuActionPerformed(evt);
            }
        });

        jLabel6.setText("Year");

        beginYearStu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007" }));

        jLabel7.setText("to");

        jLabel8.setText("Day");

        jLabel9.setText("Month");

        jLabel10.setText("Year");

        endDayStu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        endMonthStu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        endMonthStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endMonthStuActionPerformed(evt);
            }
        });

        endYearStu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007" }));

        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Gender", "Program", "Nationality"
            }
        ));
        jScrollPane1.setViewportView(showTable);

        stuReportButton.setText("OK");
        stuReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuReportButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Choose category");

        cateList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal affairs", "Lost and Found", "Academy", "School affairs" }));

        javax.swing.GroupLayout studentVisitListPanelLayout = new javax.swing.GroupLayout(studentVisitListPanel);
        studentVisitListPanel.setLayout(studentVisitListPanelLayout);
        studentVisitListPanelLayout.setHorizontalGroup(
            studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)))
                    .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(beginDayStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(endDayStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(58, 58, 58)))
                                .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(beginMonthStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(endMonthStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                .addComponent(cateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(beginYearStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endYearStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stuReportButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        studentVisitListPanelLayout.setVerticalGroup(
            studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentVisitListPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(beginDayStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(beginMonthStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(beginYearStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(studentVisitListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(endDayStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(endMonthStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(endYearStu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(cateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(stuReportButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        viewReportPanel.addTab("Student Visit List", studentVisitListPanel);

        jLabel32.setText("Input the date range from");

        jLabel33.setText("Day");

        beginDayFre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel34.setText("Month");

        beginMonthFre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        beginMonthFre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginMonthFreActionPerformed(evt);
            }
        });

        jLabel35.setText("Year");

        beginYearFre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007" }));

        jLabel36.setText("to");

        jLabel37.setText("Day");

        jLabel38.setText("Month");

        jLabel39.setText("Year");

        endDayFre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        endMonthFre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        endMonthFre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endMonthFreActionPerformed(evt);
            }
        });

        endYearFre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007" }));

        showTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Visit Frequency"
            }
        ));
        jScrollPane4.setViewportView(showTable1);

        freReportButton.setText("OK");
        freReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freReportButtonActionPerformed(evt);
            }
        });

        cateList1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal affairs", "Lost and Found", "Academy", "School affairs" }));

        reportGroup.add(jRadioButton1);
        jRadioButton1.setText("Choose by Category");

        reportGroup.add(jRadioButton2);
        jRadioButton2.setText("Choose by Gender");

        reportGroup.add(jRadioButton3);
        jRadioButton3.setText("Choose by Program");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "male", "female" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MISM", "MIST", "PPM" }));

        javax.swing.GroupLayout visitFrequencyPanelLayout = new javax.swing.GroupLayout(visitFrequencyPanel);
        visitFrequencyPanel.setLayout(visitFrequencyPanelLayout);
        visitFrequencyPanelLayout.setHorizontalGroup(
            visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(freReportButton)
                    .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel36)
                                .addComponent(jLabel32)))
                        .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(beginDayFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(endDayFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jRadioButton2))
                                .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel34)
                                        .addComponent(jLabel38))
                                    .addGap(18, 18, 18)
                                    .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(beginMonthFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endMonthFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(beginYearFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel39)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(endYearFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jRadioButton3))))
                        .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cateList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton1))
                            .addGap(73, 73, 73)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        visitFrequencyPanelLayout.setVerticalGroup(
            visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitFrequencyPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(beginDayFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(beginMonthFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(beginYearFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel36)
                .addGap(15, 15, 15)
                .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(endDayFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(endMonthFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(endYearFre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(visitFrequencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cateList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(freReportButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        viewReportPanel.addTab("Visit Frequency", visitFrequencyPanel);

        operatePanel.add(viewReportPanel, "card7");
        viewReportPanel.getAccessibleContext().setAccessibleName("tab 1");

        jLabel13.setText("Input the reason you visit");

        inputReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputReasonActionPerformed(evt);
            }
        });

        renewButton.setText("OK");
        renewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renewButtonActionPerformed(evt);
            }
        });

        jLabel31.setText("Choose Catagory");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal affairs", "Lost and Found", "Academy", "School affairs" }));

        javax.swing.GroupLayout renewVisitPanelLayout = new javax.swing.GroupLayout(renewVisitPanel);
        renewVisitPanel.setLayout(renewVisitPanelLayout);
        renewVisitPanelLayout.setHorizontalGroup(
            renewVisitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(renewVisitPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(renewVisitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(inputReason, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(363, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, renewVisitPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(renewButton)
                .addGap(153, 153, 153))
        );
        renewVisitPanelLayout.setVerticalGroup(
            renewVisitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(renewVisitPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel13)
                .addGap(46, 46, 46)
                .addComponent(inputReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(renewButton)
                .addGap(160, 160, 160))
        );

        operatePanel.add(renewVisitPanel, "card5");

        creatProButton.setText("Create");
        creatProButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatProButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel14.setText("Gender");

        jLabel15.setText("Birthday(yyyy-MM-dd)");

        jLabel16.setText("Program");

        jLabel17.setText("Reason to Visit");

        genderButtonGroup.add(Male);
        Male.setText("male");

        genderButtonGroup.add(Female);
        Female.setText("female");

        jLabel18.setText("Email");

        jLabel19.setText("Address");

        jLabel20.setText("Nationality");

        lable1.setText("Category");

        crCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal affairs", "Lost and Found", "Academy", "School affairs" }));

        javax.swing.GroupLayout creatProfilePanelLayout = new javax.swing.GroupLayout(creatProfilePanel);
        creatProfilePanel.setLayout(creatProfilePanelLayout);
        creatProfilePanelLayout.setHorizontalGroup(
            creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatProfilePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creatProfilePanelLayout.createSequentialGroup()
                        .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(creatProfilePanelLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(64, 64, 64))
                            .addComponent(jLabel18))
                        .addGap(28, 28, 28))
                    .addGroup(creatProfilePanelLayout.createSequentialGroup()
                        .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel2)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(lable1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crProgram)
                    .addComponent(crBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(crCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(crVisit, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addComponent(crNation)
                        .addComponent(crAddress)
                        .addComponent(crEmail)
                        .addComponent(crName)
                        .addGroup(creatProfilePanelLayout.createSequentialGroup()
                            .addComponent(Male)
                            .addGap(18, 18, 18)
                            .addComponent(Female))))
                .addGap(351, 351, 351))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creatProfilePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(creatProButton)
                .addGap(289, 289, 289))
        );
        creatProfilePanelLayout.setVerticalGroup(
            creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creatProfilePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Male)
                    .addComponent(Female))
                .addGap(34, 34, 34)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(crBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creatProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(crProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(crEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(crAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(crNation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(crVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(creatProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable1))
                .addGap(36, 36, 36)
                .addComponent(creatProButton)
                .addGap(53, 53, 53))
        );

        operatePanel.add(creatProfilePanel, "card6");

        jLabel41.setText("Input the student ID");

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchStudentPanelLayout = new javax.swing.GroupLayout(searchStudentPanel);
        searchStudentPanel.setLayout(searchStudentPanelLayout);
        searchStudentPanelLayout.setHorizontalGroup(
            searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStudentPanelLayout.createSequentialGroup()
                .addGroup(searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchStudentPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel41))
                    .addGroup(searchStudentPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(inputStuId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchStudentPanelLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(search)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        searchStudentPanelLayout.setVerticalGroup(
            searchStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchStudentPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(inputStuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(search)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        operatePanel.add(searchStudentPanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * "Take photo" button.
     *
     * @param evt
     */
    private void photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoActionPerformed
        //new CameraDetector();
        //CLayout.show(operatePanel, "take photo"); 
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        CameraDetector.camera();
        CameraDetector.flag = 0;
        dispose();
    }//GEN-LAST:event_photoActionPerformed

    /**
     * "View report" button.
     *
     * @param evt
     */
    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        CLayout.show(operatePanel, "report");
        // TODO add your handling code here:
    }//GEN-LAST:event_reportActionPerformed

    private void beginMonthStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginMonthStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beginMonthStuActionPerformed

    private void endMonthStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endMonthStuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endMonthStuActionPerformed

    /**
     * Report on students visiting reception by categories for a given date
     * range
     *
     * @param evt
     */
    private void stuReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuReportButtonActionPerformed
        try {
            int dayFrom = Integer.parseInt(beginDayStu.getSelectedItem().toString());
            int monthFrom = Integer.parseInt(beginMonthStu.getSelectedItem().toString());
            int yearFrom = Integer.parseInt(beginYearStu.getSelectedItem().toString());
            int dayTo = Integer.parseInt(endDayStu.getSelectedItem().toString());
            int monthTo = Integer.parseInt(endMonthStu.getSelectedItem().toString());
            int yearTo = Integer.parseInt(endYearStu.getSelectedItem().toString());

            String category = cateList.getSelectedItem().toString();

            Date dfrom = new Date((yearFrom - 1900), (monthFrom - 1), dayFrom);
            Date dto = new Date((yearTo - 1900), (monthTo - 1), dayTo);

            showTable.setModel(ReportGenerator.stuModel(stuDAO.getStudent(), dfrom, dto, category));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_stuReportButtonActionPerformed

    /**
     * create profile.
     *
     * @param evt
     */
    private void creatProButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatProButtonActionPerformed
        try {
            String name = crName.getText();
            String gender = "";
            if (Male.isSelected()) {
                gender = Male.getText();
            } else {
                gender = Female.getText();
            }

            SimpleDateFormat timeformat = new SimpleDateFormat("yyyy-MM-dd");
            Date now = new Date(System.currentTimeMillis());
            Date DOB = new Date(timeformat.parse(crBirth.getText()).getTime());
            String program = crProgram.getText();
            if (!program.equals("MISM") && !program.equals("MIST") && !program.equals("PPM")) {
                JOptionPane.showMessageDialog(this, "Invalid Program Name",
                        "error", JOptionPane.ERROR_MESSAGE);
            } else {
                String email = crEmail.getText();
                String address = crAddress.getText();
                String nation = crNation.getText();
                int id = stuDAO.getStudent().size() + 43000 + 1;
                String url = getPhotoURL;//need to be updated by the url of the phote taken by the camera
                String category = crCategory.getSelectedItem().toString();
                stuDAO.setStudent(id, name, url, DOB, program, email, address, nation, gender);
                new VisitDAO().setVisit(id, now, crVisit.getText(), category);
                CLayout.show(operatePanel, "dashboard");
                showDashBoard(id);
            }
        } catch (ParseException e1) {
            e1.printStackTrace();
            JOptionPane.showMessageDialog(this, "Invalid Birthday Format",
                    "error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException | IOException | SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_creatProButtonActionPerformed

    private void beginMonthFreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginMonthFreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beginMonthFreActionPerformed

    private void endMonthFreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endMonthFreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endMonthFreActionPerformed

    /**
     * Report on the frequency of visits to the reception by students grouped by
     * gender and categories for a specific date range.
     *
     * @param evt
     */
    private void freReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freReportButtonActionPerformed
        try {
            int dayFrom = Integer.parseInt(beginDayFre.getSelectedItem().toString());
            int monthFrom = Integer.parseInt(beginMonthFre.getSelectedItem().toString());
            int yearFrom = Integer.parseInt(beginYearFre.getSelectedItem().toString());
            int dayTo = Integer.parseInt(endDayFre.getSelectedItem().toString());
            int monthTo = Integer.parseInt(endMonthFre.getSelectedItem().toString());
            int yearTo = Integer.parseInt(endYearFre.getSelectedItem().toString());

            Date dfrom = new Date((yearFrom - 1900), (monthFrom - 1), dayFrom);
            Date dto = new Date((yearTo - 1900), (monthTo - 1), dayTo);
            String other = "";
            if (jRadioButton1.isSelected()) {
                other = cateList1.getSelectedItem().toString();
            } else if (jRadioButton2.isSelected()) {
                other = jComboBox2.getSelectedItem().toString();
            } else if (jRadioButton3.isSelected()) {
                other = jComboBox3.getSelectedItem().toString();
            }

            showTable1.setModel(ReportGenerator.freModel(stuDAO.getStudent(), dfrom, dto, other));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_freReportButtonActionPerformed

    /**
     * record student id and jump to the renew visit page.
     *
     * @param evt
     */
    private void dashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashButtonActionPerformed
        recordStudentID = Integer.parseInt(getID.getText());
        CLayout.show(operatePanel, "renew visit");

    }//GEN-LAST:event_dashButtonActionPerformed

    /**
     * jump to the search student page.
     *
     * @param evt
     */
    private void searchStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStuActionPerformed
        CLayout.show(operatePanel, "search students");
    }//GEN-LAST:event_searchStuActionPerformed

    /**
     * This method is to input student id and output information on the
     * dashboard panel.
     *
     * @param id student id
     */
    public void showDashBoard(int id) {
        try {
            Student a = new Student();
            int stuid = id;
            a = stuDAO.getStudent(stuid);
            getName.setText(a.getName());
            getGender.setText(a.getGender());
            getPro.setText(a.getProgram());
            getBirth.setText(a.getDOB().toString());
            getEmail.setText(a.getEmail());
            getAddress.setText(a.getAddress());
            getNation.setText(a.getNationality());
            getID.setText(Integer.toString(id));
            ArrayList<Visit> visitarray = a.getVisits();
            String url = a.getPhotoURL();
            Image img = javax.imageio.ImageIO.read(new File(url));
            BufferedImage resizedImage = new BufferedImage(134, 148, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = resizedImage.createGraphics();
            g.drawImage(img, 0, 0, 134, 148, null);
            g.dispose();
            getImage.setIcon(new ImageIcon(resizedImage));
            if (visitarray.isEmpty()) {
                getLastVisit.setText("No Visit");
                getReason.setText("No Visit");
            } else {
                Visit lastvisit = visitarray.get(visitarray.size() - 1);
                getLastVisit.setText(lastvisit.getTime().toString());
                getReason.setText(lastvisit.getReason());
                showVisitTable.setModel(ReportGenerator.visitModel(visitarray));
            }

            AnnDAO ann = new AnnDAO();
            Calendar cal = Calendar.getInstance();  //get current time
            int distance = 0;   //used to count the month distance
            ArrayList<Announcement> annarray = new ArrayList();     //the announcement list
            for (int i = 0; i < ann.getAnnouncement().size(); i++) {
                distance = cal.getTime().getMonth() - ann.getAnnouncement().get(i).getTime().getMonth();
                if ((distance <= 1) && (distance >= 0)) {
                    annarray.add(ann.getAnnouncement().get(i));
                }
            }
            showAnnounceTable.setModel(ReportGenerator.announceModel(annarray));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * search for student with the input id and show them on dashboard panel
     *
     * @param evt
     */
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try {

            int stuid = Integer.parseInt(inputStuId.getText());

            if ((stuid <= 43090) && (stuid >= 43000)) {
                CLayout.show(operatePanel, "dashboard");
                showDashBoard(stuid);
            } else {
                JOptionPane.showMessageDialog(searchStudentPanel, "The information of this student is not in the database");
                CameraDetector.camera();
                CameraDetector.flag = 0;
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Wrong Student Id",
                    "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * renew a visit record of a current student.
     *
     * @param evt
     */
    private void renewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renewButtonActionPerformed
        try {
            Date now = new Date(System.currentTimeMillis());

            String category = jComboBox1.getSelectedItem().toString();
            String reason = inputReason.getText();
            new VisitDAO().setVisit(recordStudentID, now, reason, category);
            JOptionPane.showMessageDialog(this, "Visit Record Has Been Renewed",
                    "Succeed", JOptionPane.PLAIN_MESSAGE);
            CLayout.show(operatePanel, "welcome");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_renewButtonActionPerformed

    private void inputReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputReasonActionPerformed

    public CardLayout getCLayout() {
        return CLayout;
    }

    public JPanel getOperatePanel() {
        return operatePanel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JComboBox beginDayFre;
    private javax.swing.JComboBox beginDayStu;
    private javax.swing.JComboBox beginMonthFre;
    private javax.swing.JComboBox beginMonthStu;
    private javax.swing.JComboBox beginYearFre;
    private javax.swing.JComboBox beginYearStu;
    private javax.swing.JComboBox cateList;
    private javax.swing.JComboBox cateList1;
    private javax.swing.JTextField crAddress;
    private javax.swing.JTextField crBirth;
    private javax.swing.JComboBox crCategory;
    private javax.swing.JTextField crEmail;
    private javax.swing.JTextField crName;
    private javax.swing.JTextField crNation;
    private javax.swing.JTextField crProgram;
    private javax.swing.JTextField crVisit;
    private javax.swing.JButton creatProButton;
    private javax.swing.JPanel creatProfilePanel;
    private javax.swing.JPanel dashBoardPanel;
    private javax.swing.JButton dashButton;
    private javax.swing.JComboBox endDayFre;
    private javax.swing.JComboBox endDayStu;
    private javax.swing.JComboBox endMonthFre;
    private javax.swing.JComboBox endMonthStu;
    private javax.swing.JComboBox endYearFre;
    private javax.swing.JComboBox endYearStu;
    private javax.swing.JButton freReportButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel getAddress;
    private javax.swing.JLabel getBirth;
    private javax.swing.JLabel getEmail;
    private javax.swing.JLabel getGender;
    private javax.swing.JLabel getID;
    private javax.swing.JLabel getImage;
    private javax.swing.JLabel getLastVisit;
    private javax.swing.JLabel getName;
    private javax.swing.JLabel getNation;
    private javax.swing.JLabel getPro;
    private javax.swing.JLabel getReason;
    private javax.swing.JTextField inputReason;
    private javax.swing.JTextField inputStuId;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lable1;
    private javax.swing.JPanel operatePanel;
    private javax.swing.JButton photo;
    private javax.swing.JButton renewButton;
    private javax.swing.JPanel renewVisitPanel;
    private javax.swing.JButton report;
    private javax.swing.ButtonGroup reportGroup;
    private javax.swing.JButton search;
    private javax.swing.JButton searchStu;
    private javax.swing.JPanel searchStudentPanel;
    private javax.swing.JTable showAnnounceTable;
    private javax.swing.JTable showTable;
    private javax.swing.JTable showTable1;
    private javax.swing.JTable showVisitTable;
    private javax.swing.JButton stuReportButton;
    private javax.swing.JPanel studentVisitListPanel;
    private javax.swing.JPanel takePhotoPanel;
    private javax.swing.JTabbedPane viewReportPanel;
    private javax.swing.JPanel visitFrequencyPanel;
    // End of variables declaration//GEN-END:variables
}
